# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Awesome Blog # the title of our blog
email: awesomeguy@awesomesite.com # our email
description: > # breaf description of our blog
  My awesome desciption.
subtitle-quote: "It is not that I'm so smart. But I stay with the questions much longer."
subtitle-author: "Albert Einstein"
baseurl: "/jekyll-tutorial" # we won't need to set that in our case
url: "http://konpa.github.io" # set it like this for now but we'll have to change this before to send it live
twitter_username: awesome_guy # your twitter username
github_username:  awesome_guy # your github username (if you have one)
disqus_shortname: awesomeblog

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3 # number of posts you want per page
